# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server/frontend

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: frontend/scripts/before_install.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: frontend/scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: frontend/scripts/app_start.sh
      timeout: 300
      runas: root